language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - composer self-update || true
    - composer install --dev --prefer-source
    - mkdir -p web/code-coverage data
    - wget https://scrutinizer-ci.com/ocular.phar

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover data/coverage.clover

script:
    - bin/atoum

notifications:
  email:
    recipients:
      - cedric@dugat.me
      - seyferseed@gmail.com
    on_success: change
    on_failure: change
